services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\GraphQL\Resolver\LocationResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Location", method: "resolveLocation" }
            - { name: overblog_graphql.resolver, alias: "LocationById", method: "resolveLocationById" }
            - { name: overblog_graphql.resolver, alias: "LocationChildren", method: "resolveLocationChildren" }
            - { name: overblog_graphql.resolver, alias: "LocationsByContentId", method: "resolveLocationsByContentId" }

    App\GraphQL\Resolver\ContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "Content", method: "resolveContent" }
            - { name: overblog_graphql.resolver, alias: "ContentById", method: "resolveContentById" }
            - { name: overblog_graphql.resolver, alias: "ContentByIdList", method: "resolveContentByIdList" }
            - { name: overblog_graphql.resolver, alias: "ContentVersions", method: "resolveContentVersions" }
            - { name: overblog_graphql.resolver, alias: "ContentByType", method: "findContentByType" }
            - { name: overblog_graphql.resolver, alias: "ContentRelations", method: "findContentRelations" }
            - { name: overblog_graphql.resolver, alias: "ContentReverseRelations", method: "findContentReverseRelations" }

    App\GraphQL\Resolver\DomainContentResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainContentItemsByTypeIdentifier", method: "resolveDomainContentItems" }
            - { name: overblog_graphql.resolver, alias: "DomainFieldValue", method: "resolveDomainFieldValue" }
            - { name: overblog_graphql.resolver, alias: "DomainContentType", method: "resolveDomainContentType" }
            - { name: overblog_graphql.resolver, alias: "DomainContentItem", method: "resolveDomainContentItem" }
            - { name: overblog_graphql.resolver, alias: "DomainRelationFieldValue", method: "resolveDomainRelationFieldValue" }
            - { name: overblog_graphql.resolver, alias: "MainUrlAlias", method: "resolveMainUrlAlias" }

    App\GraphQL\Mutation\UploadFiles:
        tags:
            - { name: overblog_graphql.mutation, alias: "UploadFiles", method: "uploadFiles" }

    App\GraphQL\Resolver\UserResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "User", method: "resolveUser" }
            - { name: overblog_graphql.resolver, alias: "UserGroups", method: "resolveUserGroups" }
            - { name: overblog_graphql.resolver, alias: "UserById", method: "resolveUserById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupsByUserId", method: "resolveUserGroupsByUserId" }
            - { name: overblog_graphql.resolver, alias: "UserGroupById", method: "resolveUserGroupById" }
            - { name: overblog_graphql.resolver, alias: "UserGroupSubGroups", method: "resolveUserGroupSubGroups" }
            - { name: overblog_graphql.resolver, alias: "UsersOfGroup", method: "resolveUsersOfGroup" }

    App\GraphQL\Resolver\ContentTypeResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "ContentTypeById", method: "resolveContentTypeById" }
            - { name: overblog_graphql.resolver, alias: "ContentType", method: "resolveContentType" }
            - { name: overblog_graphql.resolver, alias: "ContentTypesFromGroup", method: "resolveContentTypesFromGroup" }
            - { name: overblog_graphql.resolver, alias: "ContentTypeGroupByIdentifier", method: "resolveContentTypeGroupByIdentifier" }

    App\GraphQL\Resolver\FieldDefinitionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionName", method: "resolveFieldDefinitionName" }
            - { name: overblog_graphql.resolver, alias: "FieldDefinitionDescription", method: "resolveFieldDefinitionDescription" }
            - { name: overblog_graphql.resolver, alias: "SelectionFieldDefinitionOptions", method: "resolveSelectionFieldDefinitionOptions" }

    App\GraphQL\Resolver\SectionResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SectionById", method: "resolveSectionById" }

    App\GraphQL\Resolver\UrlAliasResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "UrlAliasType", method: "resolveUrlAliasType" }
            - { name: overblog_graphql.resolver, alias: "LocationUrlAliases", method: "resolveLocationUrlAliases" }

    App\GraphQL\Resolver\SearchResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SearchContent", method: "searchContent" }
            - { name: overblog_graphql.resolver, alias: "SearchContentOfTypeAsConnection", method: "searchContentOfTypeAsConnection" }

    App\GraphQL\Resolver\RichTextResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5", method: "xmlToHtml5" }
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToHtml5Edit", method: "xmlToHtml5Edit" }
            - { name: overblog_graphql.resolver, alias: "RichTextXmlToPlainText", method: "xmlToplainText" }

    App\GraphQL\Resolver\ImageFieldResolver:
        arguments:
            $variations: []
        tags:
            - { name: overblog_graphql.resolver, alias: "ImageVariations", method: "resolveImageVariations" }
            - { name: overblog_graphql.resolver, alias: "ImageVariation", method: "resolveImageVariation" }

    App\GraphQL\Resolver\DateResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DateTimeFormat", method: "resolveDateToFormat"}

    App\GraphQL\Resolver\ImageAssetFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "DomainImageAssetFieldValue", method: "resolveDomainImageAssetFieldValue"}

    App\GraphQL\Resolver\SelectionFieldResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "SelectionFieldValue", method: "resolveSelectionFieldValue"}

    App\GraphQL\Relay\NodeResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: "node", method: "resolveNode" }
            - { name: overblog_graphql.resolver, alias: "node_type", method: "resolveType" }

    App\GraphQL\Relay\SearchResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "SearchContentConnection", method: "searchContent"}

    #
    # Object States
    #

    App\GraphQL\Resolver\ObjectStateGroupResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "ObjectStateGroupById", method: "resolveObjectStateGroupById"}
            - {name: overblog_graphql.resolver, alias: "ObjectStateGroups", method: "resolveObjectStateGroups"}

    App\GraphQL\Resolver\ObjectStateResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "ObjectStateById", method: "resolveObjectStateById"}
            - {name: overblog_graphql.resolver, alias: "ObjectStateByContentInfo", method: "resolveObjectStateByContentInfo"}
            - {name: overblog_graphql.resolver, alias: "ObjectStatesByGroup", method: "resolveObjectStatesByGroup"}
            - {name: overblog_graphql.resolver, alias: "ObjectStatesByGroupId", method: "resolveObjectStatesByGroupId"}

    #
    # Content mutations
    #
    App\GraphQL\Resolver\DomainContentMutationResolver:
        tags:
            - { name: overblog_graphql.mutation, alias: "CreateDomainContent", method: "createDomainContent" }
            - { name: overblog_graphql.mutation, alias: "DeleteDomainContent", method: "deleteDomainContent" }
            - { name: overblog_graphql.mutation, alias: "UpdateDomainContent", method: "updateDomainContent" }

    App\GraphQL\Resolver\Map\UploadMap: ~
